# Generated by Django 2.2.5 on 2019-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='direct_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adspace',
            name='height',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adspace',
            name='width',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adspace',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adspace',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
