# Generated by Django 2.2.5 on 2019-10-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191001_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Buyer'),
        ),
    ]
