# Generated by Django 2.2.5 on 2019-11-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191110_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adspace',
            name='state',
            field=models.CharField(blank=True, choices=[('NY', 'NY')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='adspace',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
