# Generated by Django 2.2.5 on 2019-11-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191110_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographicprofile',
            old_name='Percent65To74',
            new_name='AgePercent65To74',
        ),
        migrations.RenameField(
            model_name='demographicprofile',
            old_name='Percent75To84',
            new_name='AgePercent75To84',
        ),
        migrations.RenameField(
            model_name='demographicprofile',
            old_name='Percent85AndOver',
            new_name='AgePercent85AndOver',
        ),
        migrations.RenameField(
            model_name='demographicprofile',
            old_name='EmployedWhiteCollar',
            new_name='WhiteCollar',
        ),
        migrations.RemoveField(
            model_name='demographicprofile',
            name='PercentGradDegree',
        ),
    ]
