# Generated by Django 2.2.5 on 2019-11-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191110_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicprofile',
            name='avgHouseholdSize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographicprofile',
            name='medianAge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographicprofile',
            name='medianIncome',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demographicprofile',
            name='populationDensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent10To14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent15To19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent20To24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent25To34',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent35To44',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent45To54',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent55To59',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent5To9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent60To64',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent65To74',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent75To84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercent85AndOver',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AgePercentUnder5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='AssocDegree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='BachDegree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='BelowHighSchool',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='BlueCollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='GradDegree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='HighSchool',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent100000To149999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent10000To14999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent150000To199999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent15000To24999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent200000OrMore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent25000To34999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent35000To49999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent50000To74999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercent75000To99999',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='IncomePercentUnder10000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentAmericanIndian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentAsian',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentBlack',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentFemale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentHispanicOrLatinoOfAnyRace',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentMale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentNotHispanicOrLatino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentOtherRace',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentPacificIslander',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='PercentWhite',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='SomeCollege',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='Unemployed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographicprofile',
            name='WhiteCollar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
