# Generated by Django 2.2.5 on 2020-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191110_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='6462203750', max_length=15, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
