# Generated by Django 2.2.5 on 2020-02-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200222_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='extension',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Company description'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_buyer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_seller',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='public_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.DeleteModel(
            name='UserExtension',
        ),
    ]
