# Generated by Django 3.0.4 on 2020-04-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200417_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdspaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='adspace_pics/default.jpg', upload_to='adspace_pics')),
                ('adspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.Adspace')),
            ],
        ),
    ]
