# Generated by Django 2.2.5 on 2019-10-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20191001_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_tags', models.TextField()),
                ('population_socioeconomic_segments', models.CharField(blank=True, choices=[('L', 'Low-Income'), ('M', 'Middle-Income'), ('H', 'High_Income')], max_length=1)),
                ('population_political_segments', models.CharField(max_length=150)),
                ('population_cultural_segments', models.CharField(max_length=150)),
                ('locations_of_business', models.TextField(blank=True)),
                ('budget', models.FloatField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
        ),
    ]
