# Generated by Django 2.2.5 on 2019-11-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191110_0427'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('Cars', 'Cars')], max_length=10)),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DemographicProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
