# Generated by Django 2.2.5 on 2019-11-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20191110_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='marketSegment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.MarketSegment'),
        ),
    ]
