# Generated by Django 2.2.5 on 2020-05-26 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_adspaceimage'),
        ('buy', '0004_auto_20191110_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='adspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.Adspace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='end',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 1, 50, 37, 184878)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='start',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 1, 51, 15, 782742)),
            preserve_default=False,
        ),
    ]
